name: changelog

on:
    pull_request:
        types:
            [
                opened,
                synchronize,
                reopened,
                ready_for_review,
                labeled,
                unlabeled
            ]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dangoslen/changelog-enforcer@v3
              with:
                  changeLogPath: CHANGELOG.md
                  skipLabels: Skip Changelog
